---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/malpania/fluxcd

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 15m
  path: "./repositories/infra-repo/apps/example-app-2/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-2