apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubevela
  namespace: vela-system
spec:
  interval: 5m
  releaseName: kubevela
  chart:
    spec:
      chart: kubevela/vela-core
      sourceRef:
        kind: HelmRepository
        name: kubevela