---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubevela
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/malpania/fluxcd

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevela
  namespace: default
spec:
  interval: 15m
  path: "./repositories/infra-repo/infra/kubevela/deploy"
  prune: false
  sourceRef:
    kind: GitRepository
    name: kubevela