---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevela
  namespace: default
spec:
  interval: 15m
  path: "./repositories/infra-repo/infra/kubevela"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubevela