---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubevela
  namespace: vela-system
spec:
  interval: 1m
  url: https://kubevela.github.io/vela-core

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubevela
  namespace: vela-system
spec:
  interval: 5m
  chart:
    spec:
      chart: vela-core
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: kubevela
        namespace: vela-system